[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/mullvad-check.sh"
interval = 10

[[block]]
block = "net"
device = "enp4s0"
format = "$icon $speed_down"

[[block]]
block = "cpu"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%a %d/%m %R') "
